DROP TABLE IF EXISTS BOOKED_PHONE;
DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS PHONE;

CREATE TABLE PERSON (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(100) NOT NULL,
  LAST_NAME VARCHAR(100) NOT NULL,
  CORP_KEY VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO PERSON(FIRST_NAME, LAST_NAME, CORP_KEY, EMAIL) VALUES ('Damian', 'Fernandez', 'uu0000', 'ing.damianfernandez@gmail.com');

CREATE TABLE PHONE (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  SERIAL_NUMBER VARCHAR(100) NOT NULL UNIQUE,
  MANUFACTURER VARCHAR(100) NOT NULL,
  MODEL VARCHAR(100) NOT NULL
);

INSERT INTO PHONE(SERIAL_NUMBER, MANUFACTURER, MODEL) VALUES ('a', 'Samsung', 'Galaxy S9');
INSERT INTO PHONE(SERIAL_NUMBER, MANUFACTURER, MODEL) VALUES ('b', 'Samsung', 'Galaxy S8');
INSERT INTO PHONE(SERIAL_NUMBER, MANUFACTURER, MODEL) VALUES ('c', 'Samsung', 'Galaxy S7');
INSERT INTO PHONE(SERIAL_NUMBER, MANUFACTURER, MODEL) VALUES ('d', 'Motorola', 'Nexus 6');
INSERT INTO PHONE(SERIAL_NUMBER, MANUFACTURER, MODEL) VALUES ('e', 'LG', 'Nexus 5X');
INSERT INTO PHONE(SERIAL_NUMBER, MANUFACTURER, MODEL) VALUES ('f', 'Huawei', 'Honor 7X');
INSERT INTO PHONE(SERIAL_NUMBER, MANUFACTURER, MODEL) VALUES ('g', 'Apple', 'iPhone X');
INSERT INTO PHONE(SERIAL_NUMBER, MANUFACTURER, MODEL) VALUES ('h', 'Apple', 'iPhone 8');
INSERT INTO PHONE(SERIAL_NUMBER, MANUFACTURER, MODEL) VALUES ('i', 'Apple', 'iPhone 4s');
INSERT INTO PHONE(SERIAL_NUMBER, MANUFACTURER, MODEL) VALUES ('j', 'Nokia', '3310');

CREATE TABLE BOOKED_PHONE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PERSON_CORP_KEY VARCHAR(100) NOT NULL,
    SERIAL_NUMBER VARCHAR(100) NOT NULL UNIQUE,
    BOOK_DATE TIMESTAMP NULL,
    CONSTRAINT FK_PERSON_CORP_KEY FOREIGN KEY(PERSON_CORP_KEY) REFERENCES PERSON(CORP_KEY),
    CONSTRAINT FK_SERIAL_NUMBER FOREIGN KEY(SERIAL_NUMBER) REFERENCES PHONE(SERIAL_NUMBER)
);

INSERT INTO BOOKED_PHONE(PERSON_CORP_KEY, SERIAL_NUMBER) VALUES ('uu0000', 'a');